source 'https://rubygems.org'

gem 'rails', '4.2.7.1'
gem 'pg', '~> 0.15'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'devise', '~> 4.3'
gem 'bootstrap-sass', '~> 3.3', '>= 3.3.6'
gem "gritter", "1.2.0"
gem "administrate"
gem "bourbon"
gem 'pundit', '~> 1.1'
gem 'puma', '~> 3.4'
gem 'twilio', '~> 3.1', '>= 3.1.1'
gem 'dotenv-rails', '~> 2.1', '>= 2.1.1'
gem 'kaminari', '1.1.0'

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails', '~> 3.o'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails', '~> 4.8'
  gem 'capybara-screenshot'
end

group :development do
  gem 'web-console', '~> 2.0'
  # gem 'spring'
end
